// #include "alldefinitions.h"
#include "clear.c"
#include "pwd.c"
#include "display.c"
#include "echo.c"
#include "cd.c"
#include "ls.c"
#include "fgproc.c"
#include "bgproc.c"
#include "pinfo.c"
#include "repeat.c"
// #include "cdrepeat.c"
#include "history.c"
#include "redirection.c"
#include "execute.c"
#include "jobs.c"
#include "bg.c"
#include "fg.c"
#include "replay.c"
// #include "checkbgprocess.c"